site_name: 软件工程复习资料

repo_name: xjsc01/SoftwareEngineeringReviewMaterials
repo_url: https://github.com/xjsc01/SoftwareEngineeringReviewMaterials/

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

  
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.top
    - navigation.sections
    - content.action.edit
    - content.tabs.link
  palette:
    primary: cyan
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      caution: octicons/zap-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
extra_css:
  - stylesheets/extra.css
